[
[ "MozAppearance", "appearance", "CSS_PROPERTY_PARSE_VALUE" , "" ],
[ "MozOutlineRadius", "_moz_outline_radius", "CSS_PROPERTY_PARSE_FUNCTION" , "" ],
[ "MozOutlineRadiusTopleft", "_moz_outline_radius_topLeft", "CSS_PROPERTY_PARSE_FUNCTION | CSS_PROPERTY_VALUE_NONNEGATIVE | CSS_PROPERTY_STORES_CALC | CSS_PROPERTY_GETCS_NEEDS_LAYOUT_FLUSH" , "" ],
[ "MozOutlineRadiusTopright", "_moz_outline_radius_topRight", "CSS_PROPERTY_PARSE_FUNCTION | CSS_PROPERTY_VALUE_NONNEGATIVE | CSS_PROPERTY_STORES_CALC | CSS_PROPERTY_GETCS_NEEDS_LAYOUT_FLUSH" , "" ],
[ "MozOutlineRadiusBottomright", "_moz_outline_radius_bottomRight", "CSS_PROPERTY_PARSE_FUNCTION | CSS_PROPERTY_VALUE_NONNEGATIVE | CSS_PROPERTY_STORES_CALC | CSS_PROPERTY_GETCS_NEEDS_LAYOUT_FLUSH" , "" ],
[ "MozOutlineRadiusBottomleft", "_moz_outline_radius_bottomLeft", "CSS_PROPERTY_PARSE_FUNCTION | CSS_PROPERTY_VALUE_NONNEGATIVE | CSS_PROPERTY_STORES_CALC | CSS_PROPERTY_GETCS_NEEDS_LAYOUT_FLUSH" , "" ],
[ "MozTabSize", "_moz_tab_size", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_VALUE_NONNEGATIVE" , "" ],
[ "All", "all", "CSS_PROPERTY_PARSE_FUNCTION" , "layout.css.all-shorthand.enabled" ],
[ "Animation", "animation", "CSS_PROPERTY_PARSE_FUNCTION" , "" ],
[ "AnimationDelay", "animation_delay", "CSS_PROPERTY_PARSE_VALUE_LIST | CSS_PROPERTY_VALUE_LIST_USES_COMMAS" , "" ],
[ "AnimationDirection", "animation_direction", "CSS_PROPERTY_PARSE_VALUE_LIST | CSS_PROPERTY_VALUE_LIST_USES_COMMAS" , "" ],
[ "AnimationDuration", "animation_duration", "CSS_PROPERTY_PARSE_VALUE_LIST | CSS_PROPERTY_VALUE_LIST_USES_COMMAS" , "" ],
[ "AnimationFillMode", "animation_fill_mode", "CSS_PROPERTY_PARSE_VALUE_LIST | CSS_PROPERTY_VALUE_LIST_USES_COMMAS" , "" ],
[ "AnimationIterationCount", "animation_iteration_count", "CSS_PROPERTY_PARSE_VALUE_LIST | CSS_PROPERTY_VALUE_NONNEGATIVE | CSS_PROPERTY_VALUE_LIST_USES_COMMAS" , "" ],
[ "AnimationName", "animation_name", "CSS_PROPERTY_PARSE_VALUE_LIST | CSS_PROPERTY_VALUE_LIST_USES_COMMAS" , "" ],
[ "AnimationPlayState", "animation_play_state", "CSS_PROPERTY_PARSE_VALUE_LIST | CSS_PROPERTY_VALUE_LIST_USES_COMMAS" , "" ],
[ "AnimationTimingFunction", "animation_timing_function", "CSS_PROPERTY_PARSE_VALUE_LIST | CSS_PROPERTY_VALUE_LIST_USES_COMMAS" , "" ],
[ "Background", "background", "CSS_PROPERTY_PARSE_FUNCTION" , "" ],
[ "BackgroundAttachment", "background_attachment", "CSS_PROPERTY_PARSE_VALUE_LIST | CSS_PROPERTY_APPLIES_TO_FIRST_LETTER_AND_FIRST_LINE | CSS_PROPERTY_APPLIES_TO_PLACEHOLDER | CSS_PROPERTY_VALUE_LIST_USES_COMMAS" , "" ],
[ "BackgroundClip", "background_clip", "CSS_PROPERTY_PARSE_VALUE_LIST | CSS_PROPERTY_APPLIES_TO_FIRST_LETTER_AND_FIRST_LINE | CSS_PROPERTY_APPLIES_TO_PLACEHOLDER | CSS_PROPERTY_VALUE_LIST_USES_COMMAS" , "" ],
[ "BackgroundColor", "background_color", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_APPLIES_TO_FIRST_LETTER_AND_FIRST_LINE | CSS_PROPERTY_APPLIES_TO_PLACEHOLDER | CSS_PROPERTY_IGNORED_WHEN_COLORS_DISABLED | CSS_PROPERTY_HASHLESS_COLOR_QUIRK" , "" ],
[ "BackgroundImage", "background_image", "CSS_PROPERTY_PARSE_VALUE_LIST | CSS_PROPERTY_APPLIES_TO_FIRST_LETTER_AND_FIRST_LINE | CSS_PROPERTY_APPLIES_TO_PLACEHOLDER | CSS_PROPERTY_VALUE_LIST_USES_COMMAS | CSS_PROPERTY_IGNORED_WHEN_COLORS_DISABLED | CSS_PROPERTY_START_IMAGE_LOADS" , "" ],
[ "MozBackgroundInlinePolicy", "_moz_background_inline_policy", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_APPLIES_TO_FIRST_LETTER_AND_FIRST_LINE | CSS_PROPERTY_APPLIES_TO_PLACEHOLDER" , "" ],
[ "BackgroundBlendMode", "background_blend_mode", "CSS_PROPERTY_PARSE_VALUE_LIST | CSS_PROPERTY_APPLIES_TO_FIRST_LETTER_AND_FIRST_LINE | CSS_PROPERTY_APPLIES_TO_PLACEHOLDER | CSS_PROPERTY_VALUE_LIST_USES_COMMAS" , "layout.css.background-blend-mode.enabled" ],
[ "BackgroundOrigin", "background_origin", "CSS_PROPERTY_PARSE_VALUE_LIST | CSS_PROPERTY_APPLIES_TO_FIRST_LETTER_AND_FIRST_LINE | CSS_PROPERTY_APPLIES_TO_PLACEHOLDER | CSS_PROPERTY_VALUE_LIST_USES_COMMAS" , "" ],
[ "BackgroundPosition", "background_position", "CSS_PROPERTY_PARSE_FUNCTION | CSS_PROPERTY_APPLIES_TO_FIRST_LETTER_AND_FIRST_LINE | CSS_PROPERTY_APPLIES_TO_PLACEHOLDER | CSS_PROPERTY_VALUE_LIST_USES_COMMAS | CSS_PROPERTY_STORES_CALC" , "" ],
[ "BackgroundRepeat", "background_repeat", "CSS_PROPERTY_PARSE_FUNCTION | CSS_PROPERTY_APPLIES_TO_FIRST_LETTER_AND_FIRST_LINE | CSS_PROPERTY_APPLIES_TO_PLACEHOLDER | CSS_PROPERTY_VALUE_LIST_USES_COMMAS" , "" ],
[ "BackgroundSize", "background_size", "CSS_PROPERTY_PARSE_FUNCTION | CSS_PROPERTY_APPLIES_TO_FIRST_LETTER_AND_FIRST_LINE | CSS_PROPERTY_APPLIES_TO_PLACEHOLDER | CSS_PROPERTY_VALUE_LIST_USES_COMMAS | CSS_PROPERTY_VALUE_NONNEGATIVE | CSS_PROPERTY_STORES_CALC" , "" ],
[ "MozBinding", "binding", "CSS_PROPERTY_PARSE_VALUE" , "" ],
[ "Border", "border", "CSS_PROPERTY_PARSE_FUNCTION" , "" ],
[ "BorderBottom", "border_bottom", "CSS_PROPERTY_PARSE_FUNCTION" , "" ],
[ "BorderBottomColor", "border_bottom_color", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_APPLIES_TO_FIRST_LETTER | CSS_PROPERTY_IGNORED_WHEN_COLORS_DISABLED | CSS_PROPERTY_HASHLESS_COLOR_QUIRK" , "" ],
[ "MozBorderBottomColors", "border_bottom_colors", "CSS_PROPERTY_PARSE_FUNCTION | CSS_PROPERTY_APPLIES_TO_FIRST_LETTER | CSS_PROPERTY_IGNORED_WHEN_COLORS_DISABLED" , "" ],
[ "BorderBottomStyle", "border_bottom_style", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_APPLIES_TO_FIRST_LETTER" , "" ],
[ "BorderBottomWidth", "border_bottom_width", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_VALUE_NONNEGATIVE | CSS_PROPERTY_APPLIES_TO_FIRST_LETTER | CSS_PROPERTY_UNITLESS_LENGTH_QUIRK | CSS_PROPERTY_GETCS_NEEDS_LAYOUT_FLUSH" , "" ],
[ "BorderCollapse", "border_collapse", "CSS_PROPERTY_PARSE_VALUE" , "" ],
[ "BorderColor", "border_color", "CSS_PROPERTY_PARSE_FUNCTION | CSS_PROPERTY_HASHLESS_COLOR_QUIRK" , "" ],
[ "MozBorderEnd", "border_end", "CSS_PROPERTY_PARSE_FUNCTION" , "" ],
[ "MozBorderEndColor", "border_end_color", "CSS_PROPERTY_PARSE_FUNCTION" , "" ],
[ "MozBorderEndStyle", "border_end_style", "CSS_PROPERTY_PARSE_FUNCTION" , "" ],
[ "MozBorderEndWidth", "border_end_width", "CSS_PROPERTY_PARSE_FUNCTION" , "" ],
[ "BorderImage", "border_image", "CSS_PROPERTY_PARSE_FUNCTION" , "" ],
[ "BorderImageSource", "border_image_source", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_APPLIES_TO_FIRST_LETTER | CSS_PROPERTY_START_IMAGE_LOADS" , "" ],
[ "BorderImageSlice", "border_image_slice", "CSS_PROPERTY_PARSE_FUNCTION | CSS_PROPERTY_APPLIES_TO_FIRST_LETTER" , "" ],
[ "BorderImageWidth", "border_image_width", "CSS_PROPERTY_PARSE_FUNCTION | CSS_PROPERTY_APPLIES_TO_FIRST_LETTER" , "" ],
[ "BorderImageOutset", "border_image_outset", "CSS_PROPERTY_PARSE_FUNCTION | CSS_PROPERTY_APPLIES_TO_FIRST_LETTER" , "" ],
[ "BorderImageRepeat", "border_image_repeat", "CSS_PROPERTY_PARSE_FUNCTION | CSS_PROPERTY_APPLIES_TO_FIRST_LETTER" , "" ],
[ "BorderLeft", "border_left", "CSS_PROPERTY_PARSE_FUNCTION" , "" ],
[ "BorderLeftColor", "border_left_color", "CSS_PROPERTY_PARSE_FUNCTION | CSS_PROPERTY_HASHLESS_COLOR_QUIRK" , "" ],
[ "MozBorderLeftColors", "border_left_colors", "CSS_PROPERTY_PARSE_FUNCTION | CSS_PROPERTY_APPLIES_TO_FIRST_LETTER | CSS_PROPERTY_IGNORED_WHEN_COLORS_DISABLED" , "" ],
[ "BorderLeftStyle", "border_left_style", "CSS_PROPERTY_PARSE_FUNCTION" , "" ],
[ "BorderLeftWidth", "border_left_width", "CSS_PROPERTY_PARSE_FUNCTION | CSS_PROPERTY_UNITLESS_LENGTH_QUIRK | CSS_PROPERTY_GETCS_NEEDS_LAYOUT_FLUSH" , "" ],
[ "BorderRight", "border_right", "CSS_PROPERTY_PARSE_FUNCTION" , "" ],
[ "BorderRightColor", "border_right_color", "CSS_PROPERTY_PARSE_FUNCTION | CSS_PROPERTY_HASHLESS_COLOR_QUIRK" , "" ],
[ "MozBorderRightColors", "border_right_colors", "CSS_PROPERTY_PARSE_FUNCTION | CSS_PROPERTY_APPLIES_TO_FIRST_LETTER | CSS_PROPERTY_IGNORED_WHEN_COLORS_DISABLED" , "" ],
[ "BorderRightStyle", "border_right_style", "CSS_PROPERTY_PARSE_FUNCTION" , "" ],
[ "BorderRightWidth", "border_right_width", "CSS_PROPERTY_PARSE_FUNCTION | CSS_PROPERTY_UNITLESS_LENGTH_QUIRK | CSS_PROPERTY_GETCS_NEEDS_LAYOUT_FLUSH" , "" ],
[ "BorderSpacing", "border_spacing", "CSS_PROPERTY_PARSE_FUNCTION | CSS_PROPERTY_VALUE_NONNEGATIVE" , "" ],
[ "MozBorderStart", "border_start", "CSS_PROPERTY_PARSE_FUNCTION" , "" ],
[ "MozBorderStartColor", "border_start_color", "CSS_PROPERTY_PARSE_FUNCTION" , "" ],
[ "MozBorderStartStyle", "border_start_style", "CSS_PROPERTY_PARSE_FUNCTION" , "" ],
[ "MozBorderStartWidth", "border_start_width", "CSS_PROPERTY_PARSE_FUNCTION" , "" ],
[ "BorderStyle", "border_style", "CSS_PROPERTY_PARSE_FUNCTION" , "" ],
[ "BorderTop", "border_top", "CSS_PROPERTY_PARSE_FUNCTION" , "" ],
[ "BorderTopColor", "border_top_color", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_APPLIES_TO_FIRST_LETTER | CSS_PROPERTY_IGNORED_WHEN_COLORS_DISABLED | CSS_PROPERTY_HASHLESS_COLOR_QUIRK" , "" ],
[ "MozBorderTopColors", "border_top_colors", "CSS_PROPERTY_PARSE_FUNCTION | CSS_PROPERTY_APPLIES_TO_FIRST_LETTER | CSS_PROPERTY_IGNORED_WHEN_COLORS_DISABLED" , "" ],
[ "BorderTopStyle", "border_top_style", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_APPLIES_TO_FIRST_LETTER" , "" ],
[ "BorderTopWidth", "border_top_width", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_VALUE_NONNEGATIVE | CSS_PROPERTY_APPLIES_TO_FIRST_LETTER | CSS_PROPERTY_UNITLESS_LENGTH_QUIRK | CSS_PROPERTY_GETCS_NEEDS_LAYOUT_FLUSH" , "" ],
[ "BorderWidth", "border_width", "CSS_PROPERTY_PARSE_FUNCTION | CSS_PROPERTY_UNITLESS_LENGTH_QUIRK" , "" ],
[ "BorderRadius", "border_radius", "CSS_PROPERTY_PARSE_FUNCTION" , "" ],
[ "BorderTopLeftRadius", "border_top_left_radius", "CSS_PROPERTY_PARSE_FUNCTION | CSS_PROPERTY_APPLIES_TO_FIRST_LETTER | CSS_PROPERTY_VALUE_NONNEGATIVE | CSS_PROPERTY_STORES_CALC | CSS_PROPERTY_GETCS_NEEDS_LAYOUT_FLUSH" , "" ],
[ "BorderTopRightRadius", "border_top_right_radius", "CSS_PROPERTY_PARSE_FUNCTION | CSS_PROPERTY_APPLIES_TO_FIRST_LETTER | CSS_PROPERTY_VALUE_NONNEGATIVE | CSS_PROPERTY_STORES_CALC | CSS_PROPERTY_GETCS_NEEDS_LAYOUT_FLUSH" , "" ],
[ "BorderBottomRightRadius", "border_bottom_right_radius", "CSS_PROPERTY_PARSE_FUNCTION | CSS_PROPERTY_APPLIES_TO_FIRST_LETTER | CSS_PROPERTY_VALUE_NONNEGATIVE | CSS_PROPERTY_STORES_CALC | CSS_PROPERTY_GETCS_NEEDS_LAYOUT_FLUSH" , "" ],
[ "BorderBottomLeftRadius", "border_bottom_left_radius", "CSS_PROPERTY_PARSE_FUNCTION | CSS_PROPERTY_APPLIES_TO_FIRST_LETTER | CSS_PROPERTY_VALUE_NONNEGATIVE | CSS_PROPERTY_STORES_CALC | CSS_PROPERTY_GETCS_NEEDS_LAYOUT_FLUSH" , "" ],
[ "Bottom", "bottom", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_STORES_CALC | CSS_PROPERTY_UNITLESS_LENGTH_QUIRK | CSS_PROPERTY_GETCS_NEEDS_LAYOUT_FLUSH" , "" ],
[ "BoxShadow", "box_shadow", "CSS_PROPERTY_PARSE_FUNCTION | CSS_PROPERTY_APPLIES_TO_FIRST_LETTER | CSS_PROPERTY_VALUE_LIST_USES_COMMAS | CSS_PROPERTY_IGNORED_WHEN_COLORS_DISABLED" , "" ],
[ "BoxSizing", "box_sizing", "CSS_PROPERTY_PARSE_VALUE" , "" ],
[ "CaptionSide", "caption_side", "CSS_PROPERTY_PARSE_VALUE" , "" ],
[ "Clear", "clear", "CSS_PROPERTY_PARSE_VALUE" , "" ],
[ "Clip", "clip", "CSS_PROPERTY_PARSE_FUNCTION | CSS_PROPERTY_UNITLESS_LENGTH_QUIRK" , "" ],
[ "Color", "color", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_APPLIES_TO_FIRST_LETTER_AND_FIRST_LINE | CSS_PROPERTY_APPLIES_TO_PLACEHOLDER | CSS_PROPERTY_IGNORED_WHEN_COLORS_DISABLED | CSS_PROPERTY_HASHLESS_COLOR_QUIRK" , "" ],
[ "MozColumns", "_moz_columns", "CSS_PROPERTY_PARSE_FUNCTION" , "" ],
[ "MozColumnCount", "_moz_column_count", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_VALUE_AT_LEAST_ONE" , "" ],
[ "MozColumnFill", "_moz_column_fill", "CSS_PROPERTY_PARSE_VALUE" , "" ],
[ "MozColumnWidth", "_moz_column_width", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_VALUE_NONNEGATIVE" , "" ],
[ "MozColumnGap", "_moz_column_gap", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_VALUE_NONNEGATIVE" , "" ],
[ "MozColumnRule", "_moz_column_rule", "CSS_PROPERTY_PARSE_FUNCTION" , "" ],
[ "MozColumnRuleColor", "_moz_column_rule_color", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_IGNORED_WHEN_COLORS_DISABLED" , "" ],
[ "MozColumnRuleStyle", "_moz_column_rule_style", "CSS_PROPERTY_PARSE_VALUE" , "" ],
[ "MozColumnRuleWidth", "_moz_column_rule_width", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_VALUE_NONNEGATIVE" , "" ],
[ "Content", "content", "CSS_PROPERTY_PARSE_FUNCTION | CSS_PROPERTY_START_IMAGE_LOADS" , "" ],
[ "CounterIncrement", "counter_increment", "CSS_PROPERTY_PARSE_FUNCTION" , "" ],
[ "CounterReset", "counter_reset", "CSS_PROPERTY_PARSE_FUNCTION" , "" ],
[ "Cursor", "cursor", "CSS_PROPERTY_PARSE_FUNCTION | CSS_PROPERTY_VALUE_LIST_USES_COMMAS | CSS_PROPERTY_START_IMAGE_LOADS | CSS_PROPERTY_IMAGE_IS_IN_ARRAY_0" , "" ],
[ "Direction", "direction", "CSS_PROPERTY_PARSE_VALUE" , "" ],
[ "Display", "display", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_APPLIES_TO_PLACEHOLDER" , "" ],
[ "EmptyCells", "empty_cells", "CSS_PROPERTY_PARSE_VALUE" , "" ],
[ "AlignContent", "align_content", "CSS_PROPERTY_PARSE_VALUE" , "" ],
[ "AlignItems", "align_items", "CSS_PROPERTY_PARSE_VALUE" , "" ],
[ "AlignSelf", "align_self", "CSS_PROPERTY_PARSE_VALUE" , "" ],
[ "Flex", "flex", "CSS_PROPERTY_PARSE_FUNCTION" , "" ],
[ "FlexBasis", "flex_basis", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_VALUE_NONNEGATIVE | CSS_PROPERTY_STORES_CALC" , "" ],
[ "FlexDirection", "flex_direction", "CSS_PROPERTY_PARSE_VALUE" , "" ],
[ "FlexFlow", "flex_flow", "CSS_PROPERTY_PARSE_FUNCTION" , "" ],
[ "FlexGrow", "flex_grow", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_VALUE_NONNEGATIVE" , "" ],
[ "FlexShrink", "flex_shrink", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_VALUE_NONNEGATIVE" , "" ],
[ "FlexWrap", "flex_wrap", "CSS_PROPERTY_PARSE_VALUE" , "" ],
[ "Order", "order", "CSS_PROPERTY_PARSE_VALUE" , "" ],
[ "JustifyContent", "justify_content", "CSS_PROPERTY_PARSE_VALUE" , "" ],
[ "CssFloat", "float", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_APPLIES_TO_FIRST_LETTER" , "" ],
[ "MozFloatEdge", "float_edge", "CSS_PROPERTY_PARSE_VALUE" , "" ],
[ "Font", "font", "CSS_PROPERTY_PARSE_FUNCTION" , "" ],
[ "FontFamily", "font_family", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_VALUE_PARSER_FUNCTION | CSS_PROPERTY_APPLIES_TO_FIRST_LETTER_AND_FIRST_LINE | CSS_PROPERTY_APPLIES_TO_PLACEHOLDER" , "" ],
[ "MozFontFeatureSettings", "font_feature_settings", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_VALUE_PARSER_FUNCTION | CSS_PROPERTY_APPLIES_TO_FIRST_LETTER_AND_FIRST_LINE | CSS_PROPERTY_APPLIES_TO_PLACEHOLDER" , "" ],
[ "FontKerning", "font_kerning", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_APPLIES_TO_FIRST_LETTER_AND_FIRST_LINE | CSS_PROPERTY_APPLIES_TO_PLACEHOLDER" , "layout.css.font-features.enabled" ],
[ "MozFontLanguageOverride", "font_language_override", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_APPLIES_TO_FIRST_LETTER_AND_FIRST_LINE | CSS_PROPERTY_APPLIES_TO_PLACEHOLDER" , "" ],
[ "FontSize", "font_size", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_VALUE_NONNEGATIVE | CSS_PROPERTY_APPLIES_TO_FIRST_LETTER_AND_FIRST_LINE | CSS_PROPERTY_APPLIES_TO_PLACEHOLDER | CSS_PROPERTY_UNITLESS_LENGTH_QUIRK" , "" ],
[ "FontSizeAdjust", "font_size_adjust", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_VALUE_NONNEGATIVE | CSS_PROPERTY_APPLIES_TO_FIRST_LETTER_AND_FIRST_LINE | CSS_PROPERTY_APPLIES_TO_PLACEHOLDER" , "" ],
[ "MozOSXFontSmoothing", "osx_font_smoothing", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_APPLIES_TO_FIRST_LETTER_AND_FIRST_LINE | CSS_PROPERTY_APPLIES_TO_PLACEHOLDER" , "layout.css.osx-font-smoothing.enabled" ],
[ "FontStretch", "font_stretch", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_APPLIES_TO_FIRST_LETTER_AND_FIRST_LINE | CSS_PROPERTY_APPLIES_TO_PLACEHOLDER" , "" ],
[ "FontStyle", "font_style", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_APPLIES_TO_FIRST_LETTER_AND_FIRST_LINE | CSS_PROPERTY_APPLIES_TO_PLACEHOLDER" , "" ],
[ "FontSynthesis", "font_synthesis", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_VALUE_PARSER_FUNCTION | CSS_PROPERTY_APPLIES_TO_FIRST_LETTER_AND_FIRST_LINE | CSS_PROPERTY_APPLIES_TO_PLACEHOLDER" , "layout.css.font-features.enabled" ],
[ "FontVariant", "font_variant", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_APPLIES_TO_FIRST_LETTER_AND_FIRST_LINE | CSS_PROPERTY_APPLIES_TO_PLACEHOLDER" , "" ],
[ "FontVariantAlternates", "font_variant_alternates", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_VALUE_PARSER_FUNCTION | CSS_PROPERTY_APPLIES_TO_FIRST_LETTER_AND_FIRST_LINE | CSS_PROPERTY_APPLIES_TO_PLACEHOLDER" , "layout.css.font-features.enabled" ],
[ "FontVariantCaps", "font_variant_caps", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_APPLIES_TO_FIRST_LETTER_AND_FIRST_LINE | CSS_PROPERTY_APPLIES_TO_PLACEHOLDER" , "layout.css.font-features.enabled" ],
[ "FontVariantEastAsian", "font_variant_east_asian", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_VALUE_PARSER_FUNCTION | CSS_PROPERTY_APPLIES_TO_FIRST_LETTER_AND_FIRST_LINE | CSS_PROPERTY_APPLIES_TO_PLACEHOLDER" , "layout.css.font-features.enabled" ],
[ "FontVariantLigatures", "font_variant_ligatures", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_VALUE_PARSER_FUNCTION | CSS_PROPERTY_APPLIES_TO_FIRST_LETTER_AND_FIRST_LINE | CSS_PROPERTY_APPLIES_TO_PLACEHOLDER" , "layout.css.font-features.enabled" ],
[ "FontVariantNumeric", "font_variant_numeric", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_VALUE_PARSER_FUNCTION | CSS_PROPERTY_APPLIES_TO_FIRST_LETTER_AND_FIRST_LINE | CSS_PROPERTY_APPLIES_TO_PLACEHOLDER" , "layout.css.font-features.enabled" ],
[ "FontVariantPosition", "font_variant_position", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_APPLIES_TO_FIRST_LETTER_AND_FIRST_LINE | CSS_PROPERTY_APPLIES_TO_PLACEHOLDER" , "layout.css.font-features.enabled" ],
[ "FontWeight", "font_weight", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_VALUE_PARSER_FUNCTION | CSS_PROPERTY_APPLIES_TO_FIRST_LETTER_AND_FIRST_LINE | CSS_PROPERTY_APPLIES_TO_PLACEHOLDER" , "" ],
[ "MozForceBrokenImageIcon", "force_broken_image_icon", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_VALUE_NONNEGATIVE" , "" ],
[ "Height", "height", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_VALUE_NONNEGATIVE | CSS_PROPERTY_STORES_CALC | CSS_PROPERTY_UNITLESS_LENGTH_QUIRK | CSS_PROPERTY_GETCS_NEEDS_LAYOUT_FLUSH" , "" ],
[ "ImageOrientation", "image_orientation", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_VALUE_PARSER_FUNCTION" , "layout.css.image-orientation.enabled" ],
[ "MozImageRegion", "image_region", "CSS_PROPERTY_PARSE_FUNCTION" , "" ],
[ "ImeMode", "ime_mode", "CSS_PROPERTY_PARSE_VALUE" , "" ],
[ "Left", "left", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_STORES_CALC | CSS_PROPERTY_UNITLESS_LENGTH_QUIRK | CSS_PROPERTY_GETCS_NEEDS_LAYOUT_FLUSH" , "" ],
[ "LetterSpacing", "letter_spacing", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_APPLIES_TO_FIRST_LETTER_AND_FIRST_LINE | CSS_PROPERTY_APPLIES_TO_PLACEHOLDER | CSS_PROPERTY_UNITLESS_LENGTH_QUIRK" , "" ],
[ "LineHeight", "line_height", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_VALUE_NONNEGATIVE | CSS_PROPERTY_APPLIES_TO_FIRST_LETTER_AND_FIRST_LINE | CSS_PROPERTY_APPLIES_TO_PLACEHOLDER | CSS_PROPERTY_GETCS_NEEDS_LAYOUT_FLUSH" , "" ],
[ "ListStyle", "list_style", "CSS_PROPERTY_PARSE_FUNCTION" , "" ],
[ "ListStyleImage", "list_style_image", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_START_IMAGE_LOADS" , "" ],
[ "ListStylePosition", "list_style_position", "CSS_PROPERTY_PARSE_VALUE" , "" ],
[ "ListStyleType", "list_style_type", "CSS_PROPERTY_PARSE_VALUE" , "" ],
[ "Margin", "margin", "CSS_PROPERTY_PARSE_FUNCTION | CSS_PROPERTY_UNITLESS_LENGTH_QUIRK | CSS_PROPERTY_APPLIES_TO_PAGE_RULE" , "" ],
[ "MarginBottom", "margin_bottom", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_APPLIES_TO_FIRST_LETTER | CSS_PROPERTY_STORES_CALC | CSS_PROPERTY_UNITLESS_LENGTH_QUIRK | CSS_PROPERTY_APPLIES_TO_PAGE_RULE | CSS_PROPERTY_GETCS_NEEDS_LAYOUT_FLUSH" , "" ],
[ "MozMarginEnd", "margin_end", "CSS_PROPERTY_PARSE_FUNCTION | CSS_PROPERTY_APPLIES_TO_PAGE_RULE" , "" ],
[ "MarginLeft", "margin_left", "CSS_PROPERTY_PARSE_FUNCTION | CSS_PROPERTY_UNITLESS_LENGTH_QUIRK | CSS_PROPERTY_APPLIES_TO_PAGE_RULE | CSS_PROPERTY_GETCS_NEEDS_LAYOUT_FLUSH" , "" ],
[ "MarginRight", "margin_right", "CSS_PROPERTY_PARSE_FUNCTION | CSS_PROPERTY_UNITLESS_LENGTH_QUIRK | CSS_PROPERTY_APPLIES_TO_PAGE_RULE | CSS_PROPERTY_GETCS_NEEDS_LAYOUT_FLUSH" , "" ],
[ "MozMarginStart", "margin_start", "CSS_PROPERTY_PARSE_FUNCTION | CSS_PROPERTY_APPLIES_TO_PAGE_RULE" , "" ],
[ "MarginTop", "margin_top", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_APPLIES_TO_FIRST_LETTER | CSS_PROPERTY_STORES_CALC | CSS_PROPERTY_UNITLESS_LENGTH_QUIRK | CSS_PROPERTY_APPLIES_TO_PAGE_RULE | CSS_PROPERTY_GETCS_NEEDS_LAYOUT_FLUSH" , "" ],
[ "MarkerOffset", "marker_offset", "CSS_PROPERTY_PARSE_VALUE" , "" ],
[ "Marks", "marks", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_VALUE_PARSER_FUNCTION" , "" ],
[ "MaxHeight", "max_height", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_VALUE_NONNEGATIVE | CSS_PROPERTY_STORES_CALC | CSS_PROPERTY_GETCS_NEEDS_LAYOUT_FLUSH" , "" ],
[ "MaxWidth", "max_width", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_VALUE_NONNEGATIVE | CSS_PROPERTY_STORES_CALC | CSS_PROPERTY_GETCS_NEEDS_LAYOUT_FLUSH" , "" ],
[ "MinHeight", "min_height", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_VALUE_NONNEGATIVE | CSS_PROPERTY_STORES_CALC | CSS_PROPERTY_GETCS_NEEDS_LAYOUT_FLUSH" , "" ],
[ "MinWidth", "min_width", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_VALUE_NONNEGATIVE | CSS_PROPERTY_STORES_CALC | CSS_PROPERTY_GETCS_NEEDS_LAYOUT_FLUSH" , "" ],
[ "MixBlendMode", "mix_blend_mode", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_CREATES_STACKING_CONTEXT" , "layout.css.mix-blend-mode.enabled" ],
[ "Opacity", "opacity", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_APPLIES_TO_PLACEHOLDER" , "" ],
[ "MozOrient", "orient", "CSS_PROPERTY_PARSE_VALUE" , "" ],
[ "Orphans", "orphans", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_VALUE_AT_LEAST_ONE" , "" ],
[ "Outline", "outline", "CSS_PROPERTY_PARSE_FUNCTION" , "" ],
[ "OutlineColor", "outline_color", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_IGNORED_WHEN_COLORS_DISABLED" , "" ],
[ "OutlineStyle", "outline_style", "CSS_PROPERTY_PARSE_VALUE" , "" ],
[ "OutlineWidth", "outline_width", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_VALUE_NONNEGATIVE" , "" ],
[ "OutlineOffset", "outline_offset", "CSS_PROPERTY_PARSE_VALUE" , "" ],
[ "Overflow", "overflow", "CSS_PROPERTY_PARSE_FUNCTION" , "" ],
[ "OverflowClipBox", "overflow_clip_box", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_ALWAYS_ENABLED_IN_UA_SHEETS | CSS_PROPERTY_APPLIES_TO_PLACEHOLDER" , "layout.css.overflow-clip-box.enabled" ],
[ "OverflowX", "overflow_x", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_APPLIES_TO_PLACEHOLDER" , "" ],
[ "OverflowY", "overflow_y", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_APPLIES_TO_PLACEHOLDER" , "" ],
[ "Padding", "padding", "CSS_PROPERTY_PARSE_FUNCTION | CSS_PROPERTY_UNITLESS_LENGTH_QUIRK" , "" ],
[ "PaddingBottom", "padding_bottom", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_VALUE_NONNEGATIVE | CSS_PROPERTY_APPLIES_TO_FIRST_LETTER | CSS_PROPERTY_APPLIES_TO_PLACEHOLDER | CSS_PROPERTY_STORES_CALC | CSS_PROPERTY_UNITLESS_LENGTH_QUIRK | CSS_PROPERTY_GETCS_NEEDS_LAYOUT_FLUSH" , "" ],
[ "MozPaddingEnd", "padding_end", "CSS_PROPERTY_PARSE_FUNCTION" , "" ],
[ "PaddingLeft", "padding_left", "CSS_PROPERTY_PARSE_FUNCTION | CSS_PROPERTY_UNITLESS_LENGTH_QUIRK | CSS_PROPERTY_GETCS_NEEDS_LAYOUT_FLUSH" , "" ],
[ "PaddingRight", "padding_right", "CSS_PROPERTY_PARSE_FUNCTION | CSS_PROPERTY_UNITLESS_LENGTH_QUIRK | CSS_PROPERTY_GETCS_NEEDS_LAYOUT_FLUSH" , "" ],
[ "MozPaddingStart", "padding_start", "CSS_PROPERTY_PARSE_FUNCTION" , "" ],
[ "PaddingTop", "padding_top", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_VALUE_NONNEGATIVE | CSS_PROPERTY_APPLIES_TO_FIRST_LETTER | CSS_PROPERTY_APPLIES_TO_PLACEHOLDER | CSS_PROPERTY_STORES_CALC | CSS_PROPERTY_UNITLESS_LENGTH_QUIRK | CSS_PROPERTY_GETCS_NEEDS_LAYOUT_FLUSH" , "" ],
[ "Page", "page", "CSS_PROPERTY_PARSE_VALUE" , "" ],
[ "PageBreakAfter", "page_break_after", "CSS_PROPERTY_PARSE_VALUE" , "" ],
[ "PageBreakBefore", "page_break_before", "CSS_PROPERTY_PARSE_VALUE" , "" ],
[ "PageBreakInside", "page_break_inside", "CSS_PROPERTY_PARSE_VALUE" , "" ],
[ "PaintOrder", "paint_order", "CSS_PROPERTY_PARSE_FUNCTION" , "svg.paint-order.enabled" ],
[ "PointerEvents", "pointer_events", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_APPLIES_TO_PLACEHOLDER" , "" ],
[ "Position", "position", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_CREATES_STACKING_CONTEXT" , "" ],
[ "Quotes", "quotes", "CSS_PROPERTY_PARSE_FUNCTION" , "" ],
[ "Resize", "resize", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_APPLIES_TO_PLACEHOLDER" , "" ],
[ "Right", "right", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_STORES_CALC | CSS_PROPERTY_UNITLESS_LENGTH_QUIRK | CSS_PROPERTY_GETCS_NEEDS_LAYOUT_FLUSH" , "" ],
[ "Size", "size", "CSS_PROPERTY_PARSE_FUNCTION" , "" ],
[ "TableLayout", "table_layout", "CSS_PROPERTY_PARSE_VALUE" , "" ],
[ "TextAlign", "text_align", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_VALUE_PARSER_FUNCTION | CSS_PROPERTY_APPLIES_TO_PLACEHOLDER" , "" ],
[ "MozTextAlignLast", "text_align_last", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_VALUE_PARSER_FUNCTION" , "" ],
[ "TextDecoration", "text_decoration", "CSS_PROPERTY_PARSE_FUNCTION" , "" ],
[ "TextCombineHorizontal", "text_combine_horizontal", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_VALUE_PARSER_FUNCTION" , "layout.css.vertical-text.enabled" ],
[ "MozTextDecorationColor", "text_decoration_color", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_APPLIES_TO_FIRST_LETTER_AND_FIRST_LINE | CSS_PROPERTY_APPLIES_TO_PLACEHOLDER | CSS_PROPERTY_IGNORED_WHEN_COLORS_DISABLED" , "" ],
[ "MozTextDecorationLine", "text_decoration_line", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_VALUE_PARSER_FUNCTION | CSS_PROPERTY_APPLIES_TO_FIRST_LETTER_AND_FIRST_LINE | CSS_PROPERTY_APPLIES_TO_PLACEHOLDER" , "" ],
[ "MozTextDecorationStyle", "text_decoration_style", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_APPLIES_TO_FIRST_LETTER_AND_FIRST_LINE | CSS_PROPERTY_APPLIES_TO_PLACEHOLDER" , "" ],
[ "TextIndent", "text_indent", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_STORES_CALC | CSS_PROPERTY_GETCS_NEEDS_LAYOUT_FLUSH" , "" ],
[ "TextOrientation", "text_orientation", "CSS_PROPERTY_PARSE_VALUE" , "layout.css.vertical-text.enabled" ],
[ "TextOverflow", "text_overflow", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_VALUE_PARSER_FUNCTION | CSS_PROPERTY_APPLIES_TO_PLACEHOLDER" , "" ],
[ "TextShadow", "text_shadow", "CSS_PROPERTY_PARSE_FUNCTION | CSS_PROPERTY_APPLIES_TO_FIRST_LETTER_AND_FIRST_LINE | CSS_PROPERTY_APPLIES_TO_PLACEHOLDER | CSS_PROPERTY_VALUE_LIST_USES_COMMAS | CSS_PROPERTY_IGNORED_WHEN_COLORS_DISABLED" , "" ],
[ "MozTextSizeAdjust", "text_size_adjust", "CSS_PROPERTY_PARSE_VALUE" , "" ],
[ "TextTransform", "text_transform", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_APPLIES_TO_FIRST_LETTER_AND_FIRST_LINE | CSS_PROPERTY_APPLIES_TO_PLACEHOLDER" , "" ],
[ "Transform", "transform", "CSS_PROPERTY_PARSE_FUNCTION | CSS_PROPERTY_GETCS_NEEDS_LAYOUT_FLUSH | CSS_PROPERTY_CREATES_STACKING_CONTEXT" , "" ],
[ "TransformOrigin", "transform_origin", "CSS_PROPERTY_PARSE_FUNCTION | CSS_PROPERTY_STORES_CALC | CSS_PROPERTY_GETCS_NEEDS_LAYOUT_FLUSH" , "" ],
[ "PerspectiveOrigin", "perspective_origin", "CSS_PROPERTY_PARSE_FUNCTION | CSS_PROPERTY_STORES_CALC | CSS_PROPERTY_GETCS_NEEDS_LAYOUT_FLUSH" , "" ],
[ "Perspective", "perspective", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_CREATES_STACKING_CONTEXT" , "" ],
[ "TransformStyle", "transform_style", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_CREATES_STACKING_CONTEXT" , "" ],
[ "BackfaceVisibility", "backface_visibility", "CSS_PROPERTY_PARSE_VALUE" , "" ],
[ "Top", "top", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_STORES_CALC | CSS_PROPERTY_UNITLESS_LENGTH_QUIRK | CSS_PROPERTY_GETCS_NEEDS_LAYOUT_FLUSH" , "" ],
 [ "TouchAction", "touch_action", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_VALUE_PARSER_FUNCTION" , "layout.css.touch_action.enabled" ],
[ "Transition", "transition", "CSS_PROPERTY_PARSE_FUNCTION" , "" ],
[ "TransitionDelay", "transition_delay", "CSS_PROPERTY_PARSE_VALUE_LIST | CSS_PROPERTY_VALUE_LIST_USES_COMMAS" , "" ],
[ "TransitionDuration", "transition_duration", "CSS_PROPERTY_PARSE_VALUE_LIST | CSS_PROPERTY_VALUE_LIST_USES_COMMAS" , "" ],
[ "TransitionProperty", "transition_property", "CSS_PROPERTY_PARSE_FUNCTION | CSS_PROPERTY_VALUE_LIST_USES_COMMAS" , "" ],
[ "TransitionTimingFunction", "transition_timing_function", "CSS_PROPERTY_PARSE_VALUE_LIST | CSS_PROPERTY_VALUE_LIST_USES_COMMAS" , "" ],
[ "UnicodeBidi", "unicode_bidi", "CSS_PROPERTY_PARSE_VALUE" , "" ],
[ "MozUserFocus", "user_focus", "CSS_PROPERTY_PARSE_VALUE" , "" ],
[ "MozUserInput", "user_input", "CSS_PROPERTY_PARSE_VALUE" , "" ],
[ "MozUserModify", "user_modify", "CSS_PROPERTY_PARSE_VALUE" , "" ],
[ "MozUserSelect", "user_select", "CSS_PROPERTY_PARSE_VALUE" , "" ],
[ "VerticalAlign", "vertical_align", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_APPLIES_TO_FIRST_LETTER_AND_FIRST_LINE | CSS_PROPERTY_APPLIES_TO_PLACEHOLDER | CSS_PROPERTY_STORES_CALC | CSS_PROPERTY_GETCS_NEEDS_LAYOUT_FLUSH" , "" ],
[ "Visibility", "visibility", "CSS_PROPERTY_PARSE_VALUE" , "" ],
[ "WhiteSpace", "white_space", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_APPLIES_TO_PLACEHOLDER" , "" ],
[ "Widows", "widows", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_VALUE_AT_LEAST_ONE" , "" ],
[ "Width", "width", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_VALUE_NONNEGATIVE | CSS_PROPERTY_STORES_CALC | CSS_PROPERTY_UNITLESS_LENGTH_QUIRK | CSS_PROPERTY_GETCS_NEEDS_LAYOUT_FLUSH" , "" ],
[ "MozWindowShadow", "_moz_window_shadow", "CSS_PROPERTY_PARSE_VALUE" , "" ],
[ "WordBreak", "word_break", "CSS_PROPERTY_PARSE_VALUE" , "" ],
[ "WordSpacing", "word_spacing", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_APPLIES_TO_FIRST_LETTER_AND_FIRST_LINE | CSS_PROPERTY_APPLIES_TO_PLACEHOLDER | CSS_PROPERTY_UNITLESS_LENGTH_QUIRK" , "" ],
[ "WordWrap", "word_wrap", "CSS_PROPERTY_PARSE_VALUE" , "" ],
[ "MozHyphens", "hyphens", "CSS_PROPERTY_PARSE_VALUE" , "" ],
[ "WritingMode", "writing_mode", "CSS_PROPERTY_PARSE_VALUE" , "layout.css.vertical-text.enabled" ],
[ "ZIndex", "z_index", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_CREATES_STACKING_CONTEXT" , "" ],
[ "MozBoxAlign", "box_align", "CSS_PROPERTY_PARSE_VALUE" , "" ],
[ "MozBoxDirection", "box_direction", "CSS_PROPERTY_PARSE_VALUE" , "" ],
[ "MozBoxFlex", "box_flex", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_VALUE_NONNEGATIVE" , "" ],
[ "MozBoxOrient", "box_orient", "CSS_PROPERTY_PARSE_VALUE" , "" ],
[ "MozBoxPack", "box_pack", "CSS_PROPERTY_PARSE_VALUE" , "" ],
[ "MozBoxOrdinalGroup", "box_ordinal_group", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_VALUE_NONNEGATIVE" , "" ],
[ "MozStackSizing", "stack_sizing", "CSS_PROPERTY_PARSE_VALUE" , "" ],
[ "ClipPath", "clip_path", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_CREATES_STACKING_CONTEXT" , "" ],
[ "ClipRule", "clip_rule", "CSS_PROPERTY_PARSE_VALUE" , "" ],
[ "ColorInterpolation", "color_interpolation", "CSS_PROPERTY_PARSE_VALUE" , "" ],
[ "ColorInterpolationFilters", "color_interpolation_filters", "CSS_PROPERTY_PARSE_VALUE" , "" ],
[ "DominantBaseline", "dominant_baseline", "CSS_PROPERTY_PARSE_VALUE" , "" ],
[ "Fill", "fill", "CSS_PROPERTY_PARSE_FUNCTION" , "" ],
[ "FillOpacity", "fill_opacity", "CSS_PROPERTY_PARSE_VALUE" , "" ],
[ "FillRule", "fill_rule", "CSS_PROPERTY_PARSE_VALUE" , "" ],
[ "Filter", "filter", "CSS_PROPERTY_PARSE_FUNCTION | CSS_PROPERTY_CREATES_STACKING_CONTEXT" , "" ],
[ "FloodColor", "flood_color", "CSS_PROPERTY_PARSE_VALUE" , "" ],
[ "FloodOpacity", "flood_opacity", "CSS_PROPERTY_PARSE_VALUE" , "" ],
[ "ImageRendering", "image_rendering", "CSS_PROPERTY_PARSE_VALUE" , "" ],
[ "LightingColor", "lighting_color", "CSS_PROPERTY_PARSE_VALUE" , "" ],
[ "Marker", "marker", "CSS_PROPERTY_PARSE_FUNCTION" , "" ],
[ "MarkerEnd", "marker_end", "CSS_PROPERTY_PARSE_VALUE" , "" ],
[ "MarkerMid", "marker_mid", "CSS_PROPERTY_PARSE_VALUE" , "" ],
[ "MarkerStart", "marker_start", "CSS_PROPERTY_PARSE_VALUE" , "" ],
[ "Mask", "mask", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_CREATES_STACKING_CONTEXT" , "" ],
[ "MaskType", "mask_type", "CSS_PROPERTY_PARSE_VALUE" , "layout.css.masking.enabled" ],
[ "ShapeRendering", "shape_rendering", "CSS_PROPERTY_PARSE_VALUE" , "" ],
[ "StopColor", "stop_color", "CSS_PROPERTY_PARSE_VALUE" , "" ],
[ "StopOpacity", "stop_opacity", "CSS_PROPERTY_PARSE_VALUE" , "" ],
[ "Stroke", "stroke", "CSS_PROPERTY_PARSE_FUNCTION" , "" ],
[ "StrokeDasharray", "stroke_dasharray", "CSS_PROPERTY_PARSE_FUNCTION | CSS_PROPERTY_VALUE_LIST_USES_COMMAS" , "" ],
[ "StrokeDashoffset", "stroke_dashoffset", "CSS_PROPERTY_PARSE_VALUE" , "" ],
[ "StrokeLinecap", "stroke_linecap", "CSS_PROPERTY_PARSE_VALUE" , "" ],
[ "StrokeLinejoin", "stroke_linejoin", "CSS_PROPERTY_PARSE_VALUE" , "" ],
[ "StrokeMiterlimit", "stroke_miterlimit", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_VALUE_AT_LEAST_ONE" , "" ],
[ "StrokeOpacity", "stroke_opacity", "CSS_PROPERTY_PARSE_VALUE" , "" ],
[ "StrokeWidth", "stroke_width", "CSS_PROPERTY_PARSE_VALUE | CSS_PROPERTY_VALUE_NONNEGATIVE" , "" ],
[ "TextAnchor", "text_anchor", "CSS_PROPERTY_PARSE_VALUE" , "" ],
[ "TextRendering", "text_rendering", "CSS_PROPERTY_PARSE_VALUE" , "" ],
[ "VectorEffect", "vector_effect", "CSS_PROPERTY_PARSE_VALUE" , "" ],
[ "WillChange", "will_change", "CSS_PROPERTY_PARSE_FUNCTION | CSS_PROPERTY_VALUE_LIST_USES_COMMAS | CSS_PROPERTY_ALWAYS_ENABLED_IN_CHROME_OR_CERTIFIED_APP" , "layout.css.will-change.enabled" ],
[ "MozTransform", "_moz_transform", "CSS_PROPERTY_PARSE_FUNCTION | CSS_PROPERTY_IS_ALIAS" , "layout.css.prefixes.transforms" ],
[ "MozTransformOrigin", "transform_origin", "0" , "layout.css.prefixes.transforms" ],
[ "MozPerspectiveOrigin", "perspective_origin", "0" , "layout.css.prefixes.transforms" ],
[ "MozPerspective", "perspective", "0" , "layout.css.prefixes.transforms" ],
[ "MozTransformStyle", "transform_style", "0" , "layout.css.prefixes.transforms" ],
[ "MozBackfaceVisibility", "backface_visibility", "0" , "layout.css.prefixes.transforms" ],
[ "MozBorderImage", "border_image", "0" , "layout.css.prefixes.border-image" ],
[ "MozTransition", "transition", "0" , "layout.css.prefixes.transitions" ],
[ "MozTransitionDelay", "transition_delay", "0" , "layout.css.prefixes.transitions" ],
[ "MozTransitionDuration", "transition_duration", "0" , "layout.css.prefixes.transitions" ],
[ "MozTransitionProperty", "transition_property", "0" , "layout.css.prefixes.transitions" ],
[ "MozTransitionTimingFunction", "transition_timing_function", "0" , "layout.css.prefixes.transitions" ],
[ "MozAnimation", "animation", "0" , "layout.css.prefixes.animations" ],
[ "MozAnimationDelay", "animation_delay", "0" , "layout.css.prefixes.animations" ],
[ "MozAnimationDirection", "animation_direction", "0" , "layout.css.prefixes.animations" ],
[ "MozAnimationDuration", "animation_duration", "0" , "layout.css.prefixes.animations" ],
[ "MozAnimationFillMode", "animation_fill_mode", "0" , "layout.css.prefixes.animations" ],
[ "MozAnimationIterationCount", "animation_iteration_count", "0" , "layout.css.prefixes.animations" ],
[ "MozAnimationName", "animation_name", "0" , "layout.css.prefixes.animations" ],
[ "MozAnimationPlayState", "animation_play_state", "0" , "layout.css.prefixes.animations" ],
[ "MozAnimationTimingFunction", "animation_timing_function", "0" , "layout.css.prefixes.animations" ],
[ "MozBoxSizing", "box_sizing", "0" , "layout.css.prefixes.box-sizing" ],
[ "FontFeatureSettings", "font_feature_settings", "0" , "layout.css.font-features.enabled" ],
[ "FontLanguageOverride", "font_language_override", "0" , "layout.css.font-features.enabled" ],







]
